on:
  push:
jobs:
  testa:
    strategy:
      matrix:
        package: ${{ fromJSON('["A", "B", "C"]') }}
    runs-on: ubuntu-latest
    steps:
    # output what you want, the output of package B will be available in needs for furture jobs
    - run: echo "MyKey_${{ matrix.package }}=MyOutput" > $GITHUB_OUTPUT
      id: mystep
      if: matrix.package != 'B' 
    outputs:
      resultat: ${{ toJSON(steps.mystep.outputs) }}
  testb:
    runs-on: ubuntu-latest
    needs: testa
    steps:
    - run: ${{ tojson(needs) }}
      shell: cat {0}
